version: 2
linters:
  disable:
    - errcheck  # Pre-existing issues, not introduced by this PR
  enable:
    - govet
    - staticcheck

linters-settings:
  staticcheck:
    checks: ["all", "-SA1019"]  # SA1019 is handled by //lint:ignore directives for CI's staticcheck
